name       : haskell-pipes
version    : 4.3.2
release    : 1
source     :
    - https://hackage.haskell.org/package/pipes-4.3.2/pipes-4.3.2.tar.gz : 7957bb290db7f1dfad0581f363ab97fcd58f7c0b916e1114464cb9a398b8334a
license    : BSD-3-Clause
component  : programming.haskell
summary    : pipes is a clean and powerful stream processing library that lets you build and connect reusable streaming components
description: |
    pipes is a clean and powerful stream processing library that lets you build and connect reusable streaming components
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions
    - haskell-mmorph
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
