name       : haskell-pipes
version    : 4.3.9
release    : 2
source     :
    - https://hackage.haskell.org/package/pipes-4.3.9/pipes-4.3.9.tar.gz : 5c4cda351f9cf59376832baaeb857db25bd4990fd78c4b061aca0bde47271acb
license    : BSD-3-Clause
component  : programming.haskell
summary    : pipes is a clean and powerful stream processing library that lets you build and connect reusable streaming components
description: |
    pipes is a clean and powerful stream processing library that lets you build and connect reusable streaming components
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions
    - haskell-mmorph
    - haskell-semigroups
    - haskell-void
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
