name       : haskell-pipes
version    : 4.3.13
release    : 3
source     :
    - https://hackage.haskell.org/package/pipes-4.3.13/pipes-4.3.13.tar.gz : 76ba4f2832dae70b5f8d97e16fadd766c097f9bcd96b3a9abec0c5e24aee03b2
license    : BSD-3-Clause
component  : programming.haskell
summary    : pipes is a clean and powerful stream processing library that lets you build and connect reusable streaming components
description: |
    pipes is a clean and powerful stream processing library that lets you build and connect reusable streaming components
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions-devel
    - haskell-mmorph-devel
    - haskell-semigroups-devel
    - haskell-void-devel
rundeps    :
    - devel:
        - haskell-exceptions-devel
        - haskell-mmorph-devel
        - haskell-semigroups-devel
        - haskell-void-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
